name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Select the environment'
        required: true
        default: 'Develop'
        type: choice
        options:
          - Develop
          - Release

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ''

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Determine Environment
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Develop" ]; then
            echo "ENVIRONMENT=Development" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "Release" ]; then
            echo "ENVIRONMENT=Release" >> $GITHUB_ENV
          fi

      - name: Validate Release Branch (for Release environment only)
        if: ${{ github.event.inputs.environment == 'Release' }}
        run: |
          if [[ ! "${{ github.event.inputs.branch }}" =~ ^releases/ ]]; then
            echo "Error: Release deployments must use a branch starting with 'releases/'." >&2
            exit 1
          fi

      - name: Deploy Application
        run: |
          echo "Deploying branch ${{ github.event.inputs.branch }} to $ENVIRONMENT environment"
          # Add your deployment commands here

      - name: Confirm Deployment
        run: |
          echo "Deployment to $ENVIRONMENT environment completed."
