name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to trigger the workflow'
        type: string
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch_name }}
    - run: |
        echo "The workflow was triggered on branch: ${{ github.event.inputs.branch_name }}"
    - run: |
        git checkout ${{ github.event.inputs.branch_name }}
        # Your build commands here