name: Deploy Workflow (Windows)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'Develop'
        type: choice
        options:
          - Develop
          - Release

env:
  ENVIRONMENT: ''

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Environment Variable
        shell: pwsh
        run: |
          $inputEnvironment = "${{ github.event.inputs.environment }}"
          if ($inputEnvironment -eq "Develop") {
            $env:ENVIRONMENT = "Development"
            $env:CHANNEL = "Default"
          } elseif ($inputEnvironment -eq "Release") {
            $env:ENVIRONMENT = "UAT"
            $env:CHANNEL = "Release"
          }
          fi
          echo "ENVIRONMENT=$env:ENVIRONMENT" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "CHANNEL=$env:CHANNEL" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Print Environment and Channel
        shell: pwsh
        run: |
          echo "The ENVIRONMENT is set to: $env:ENVIRONMENT"
          echo "The CHANNEL is set to: $env:CHANNEL"

      - name: Confirm Deployment
        shell: pwsh
        run: |
          echo "Deployment to ${{env.ENVIRONMENT}} environment completed."

      - name: Install dependencies
        shell: pwsh
        run: |
          echo "Installing dependencies for $env:ENVIRONMENT environment..."

      - name: Deploy Application
        shell: pwsh
        run: |
          echo "Deploying branch ${{ github.event.inputs.branch }} to $env:ENVIRONMENT environment..."

      - name: Run application
        shell: pwsh
        run: |
          echo "$env:ENVIRONMENT application is running..."
