name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'Develop'
        type: choice
        options:
          - Develop
          - Release

env:
  ENVIRONMENT: ""

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Environment Variable
        run: |
          if (${github.event.inputs.environment} -eq "Develop") {
            Write-Host "##vso[task.setvariable variable=ENVIRONMENT]Development"
          } elseif (${github.event.inputs.environment} -eq "Release") {
            Write-Host "##vso[task.setvariable variable=ENVIRONMENT]UAT"
          }

      - name: Print Environment
        run: |
          Write-Host "The ENVIRONMENT is set to: ${{env.ENVIRONMENT}}"

      - name: Confirm Deployment
        run: |
          Write-Host "Deployment to ${{env.ENVIRONMENT}} environment completed."

      - name: Install dependencies
        run: |
          # Replace with your Windows-specific dependency installation commands
          Write-Host "Installing dependencies for ${{env.ENVIRONMENT}} environment..."

      - name: Deploy Application
        run: |
          # Replace with your Windows-specific deployment commands
          Write-Host "Deploying branch ${{ github.event.inputs.branch }} to ${{env.ENVIRONMENT}} environment..."

      - name: Run application
        run: |
          # Replace with your Windows-specific application startup commands
          Write-Host "${{env.ENVIRONMENT}} application is running..."