name: Deploy Workflow (Windows)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'Develop'
        type: choice
        options:
          - Develop
          - Release

env:
  ENVIRONMENT: ''

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Environment Variable
        run: |
          if "%{{ github.event.inputs.environment }}" == "Develop" (
            set ENVIRONMENT=Development
          ) else if "%{{ github.event.inputs.environment }}" == "Release" (
            set ENVIRONMENT=UAT
          )
          echo ENVIRONMENT=%ENVIRONMENT% >> $GITHUB_ENV

      - name: Print Environment
        run: |
          echo The ENVIRONMENT is set to: %ENVIRONMENT%
          
      - name: Confirm Deployment
        run: |
          echo Deployment to %ENVIRONMENT% environment completed.
      
      - name: Install dependencies
        run: |
          echo Installing dependencies for %ENVIRONMENT% environment...

      - name: Deploy Application
        run: |
          echo Deploying branch %{{ github.event.inputs.branch }} to %ENVIRONMENT% environment...

      - name: Run application
        run: |
          echo %ENVIRONMENT% application is running...
