name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'Develop'
        type: choice
        options:
          - Develop
          - Release

env:
  ENVIRONMENT: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Environment Variable
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Develop" ]; then
            echo "ENVIRONMENT=Development" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "Release" ]; then
            echo "ENVIRONMENT=UAT" >> $GITHUB_ENV
          fi

      - name: Print Environment
        run: |
          echo "The ENVIRONMENT is set to: ${{ env.ENVIRONMENT }}"

      - name: Confirm Deployment
        run: |
          echo "Deployment to ${{ env.ENVIRONMENT }} environment completed."

      - name: Install dependencies
        run: |
          echo "Installing dependencies for ${{ env.ENVIRONMENT }} environment..."

      - name: Deploy Application
        run: |
          echo "Deploying branch ${{ github.event.inputs.branch }} to ${{ env.ENVIRONMENT }} environment..."

      - name: Run application
        run: |
          echo "${{ env.ENVIRONMENT }} application is running..."