name: CI pipeline

on: 
  push:
    branch:
      - develop
      - release

jobs:
  build-deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies for develop
      run: |
        echo "Installing dev dependencies"

    - name: Run dev application
      run: |
        echo "dev application running..."

  build-release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      users: actions/checkout@v2

    - name: Install dependencies for release
      run: |
        echo "Installing release dependencies..."

    - name: Run release application
      run: |
        echo "release application running..."
